export { applyInput, applyInputP5, applyInputQR } from "./applyInput";
export { detectCollisions } from "./detectCollisions";
export { enforceCollisions } from "./enforceCollisions";
export { pollInput, pollInputsP5, pollInputQR } from "./pollInputs";
export { spawnFood } from "./spawnFood";
export { syncRenderer, syncRendererP5 } from "./syncRenderer";
export { updateGrid } from "./updateGrid";
export { updateMovement, updateMovementP5 } from "./updateMovement";
export { updatePlayerView } from "./updatePlayerView";
export { updateSegments } from "./updateSegments";
export { updateTime } from "./updateTime";
export { showSplashScreen } from "./showSplashScreen";
